# Generated by Django 4.1.7 on 2023-06-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0002_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, default='media/avatares/avatar_anonimo.png', null=True, upload_to='media/avatares'),
        ),
    ]
