# Generated by Django 4.1.7 on 2023-06-17 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_ppal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
