# Generated by Django 4.1.7 on 2023-06-20 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_ppal', '0003_post_delete_curso_delete_entregable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='autor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
