# Generated by Django 4.1.7 on 2023-06-21 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_ppal', '0006_chat_comment_fecha_post_fecha_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='usuario2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats2', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario'),
        ),
    ]
