# Generated by Django 4.1.7 on 2023-06-21 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_ppal', '0007_alter_chat_usuario2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='web_ppal.chat'),
        ),
    ]
