# Generated by Django 4.1.7 on 2023-06-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_ppal', '0009_post_subtitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, default='posteos/avatar_anonimo.png', null=True, upload_to='posteos'),
        ),
    ]
