# Generated by Django 4.1.7 on 2023-06-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_ppal', '0010_alter_post_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='posteos'),
        ),
    ]
